repos:
  # Spell checking for text, markdown, and YAML files
  - repo: local
    hooks:
      - id: cspell
        name: Spell Checker
        entry: npx cspell
        language: node
        types: [text, yaml, markdown]
        args:
          - '--config=./cspell.json'

  # Security analysis for Python code
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: Security Analysis
        entry: bandit
        language: python
        types: [python]
        args:
          - '-r'  # Recursively analyze code

  # General-purpose pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        name: End of File Fixer
        description: Ensure files end with a newline.
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=500']

  # Python formatter (PEP 8 compliant)
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.12

  # Import sorter (PEP 8 compliant)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  # Python linter and style checker
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
